stages:
  ingest:
    cmd: python src/ingestion.py
    deps:
      - src/ingestion.py
    outs:
      - data/raw/gossipcop_combined.csv
  preprocess:
    cmd: python src/preprocessing.py
    deps:
      - data/raw/gossipcop_combined.csv
      - src/preprocessing.py
    outs:
      - data/processed/gossipcop_cleaned.csv
  train:
    cmd: python src/train.py
    deps:
      - data/processed/gossipcop_cleaned.csv
      - src/train.py
    outs:
      - models/cnn_v1.h5
      - models/tokenizer.pkl

